parameters:
- name: env
  displayName: Select environment
  type: string
  default: dev
  values:
  - dev
  - prod
- name: action
  displayName: Select terraform action
  type: string
  default: apply
  values:
  - apply
  - destroy

trigger:
- main

pr:
  branches:
    include:
    - '*'

stages:
- stage: Plan
  condition: eq(variables['Build.Reason'], 'PullRequest')
  jobs:
  - job: terraformPlan
    pool:
      name: 'my-pool'
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
        
    - task: TerraformTaskV4@4
      displayName: 'Terraform Init'
      inputs:
        provider: 'aws'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        backendServiceAWS: 'aws_terraform'
        backendAWSBucketName: 'terraform-state-mina-lab'
        backendAWSKey: 'terraform.tfstate'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Plan'
      env:
        TF_VAR_rds_username: $(TF_VAR_rds_username)
        TF_VAR_rds_password: $(TF_VAR_rds_password)
      inputs:
        provider: 'aws'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        commandOptions: '-var-file="${{ parameters.env }}.tfvars"'
        environmentServiceNameAWS: 'aws_terraform'

- stage: Apply
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq('${{ parameters.action }}', 'apply'))
  jobs:
  - job: terraformApply
    pool:
      name: 'my-pool'
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    
    - task: TerraformTaskV4@4
      displayName: 'Terraform Init'
      inputs:
        provider: 'aws'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        backendServiceAWS: 'aws_terraform'
        backendAWSBucketName: 'terraform-state-mina-lab'
        backendAWSKey: 'terraform.tfstate'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Apply'
      env:
        TF_VAR_rds_username: $(TF_VAR_rds_username)
        TF_VAR_rds_password: $(TF_VAR_rds_password)
      inputs:
        provider: 'aws'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        commandOptions: '-var-file="${{ parameters.env }}.tfvars"'
        environmentServiceNameAWS: 'aws_terraform'

- stage: Destroy
  condition: and(succeeded(), eq('${{ parameters.action }}', 'destroy'))
  jobs:
  - job: terraformDestroy
    pool:
      name: 'my-pool'
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    
    - task: TerraformTaskV4@4
      displayName: 'Terraform Init'
      inputs:
        provider: 'aws'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        backendServiceAWS: 'aws_terraform'
        backendAWSBucketName: 'terraform-state-mina-lab'
        backendAWSKey: 'terraform.tfstate'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Destroy'
      env:
        TF_VAR_rds_username: $(TF_VAR_rds_username)
        TF_VAR_rds_password: $(TF_VAR_rds_password)
      inputs:
        provider: 'aws'
        command: 'destroy'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        commandOptions: '-var-file="${{ parameters.env }}.tfvars"'
        environmentServiceNameAWS: 'aws_terraform'
